version: '3.9'
name: deeptruth_db

services:
  postgres_db:
    image: postgres

    environment:
      POSTGRES_DB: deeptruth
      POSTGRES_PASSWORD: "qwerty"

    volumes:
      - ./internal/db/dumps:/dumps
      - postgres_data:/var/lib/postgresql/data
  
  app:
    container_name: deeptruth_runtime
    build: .
    ports:
      - "8083:8083"
    depends_on:
      - postgres_db
    links:
      - "postgres_db:db"

volumes:
  postgres_data:
