// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: author.sql

package db

import (
	"context"
	"time"
)

const createAuthor = `-- name: CreateAuthor :one
INSERT INTO authors (
    name,
    rating,
    description,
    created_at
) VALUES (
    $1, $2, $3, $4
) RETURNING id, name, description, rating, created_at
`

type CreateAuthorParams struct {
	Name        string
	Rating      int64
	Description string
	CreatedAt   time.Time
}

func (q *Queries) CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, createAuthor,
		arg.Name,
		arg.Rating,
		arg.Description,
		arg.CreatedAt,
	)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAuthor = `-- name: DeleteAuthor :exec
DELETE FROM authors WHERE id = $1
`

func (q *Queries) DeleteAuthor(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAuthor, id)
	return err
}

const getAuthor = `-- name: GetAuthor :one
SELECT id, name, description, rating, created_at FROM authors 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAuthor(ctx context.Context, id int64) (Author, error) {
	row := q.db.QueryRow(ctx, getAuthor, id)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}

const listAuthor = `-- name: ListAuthor :many
SELECT id, name, description, rating, created_at FROM authors
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAuthorParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListAuthor(ctx context.Context, arg ListAuthorParams) ([]Author, error) {
	rows, err := q.db.Query(ctx, listAuthor, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Author
	for rows.Next() {
		var i Author
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Rating,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAuthor = `-- name: UpdateAuthor :one
UPDATE authors
SET rating = $2
WHERE id = $1
RETURNING id, name, description, rating, created_at
`

type UpdateAuthorParams struct {
	ID     int64
	Rating int64
}

func (q *Queries) UpdateAuthor(ctx context.Context, arg UpdateAuthorParams) (Author, error) {
	row := q.db.QueryRow(ctx, updateAuthor, arg.ID, arg.Rating)
	var i Author
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Rating,
		&i.CreatedAt,
	)
	return i, err
}
