// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Article struct {
	ID       int64
	AuthorID pgtype.Int8
	Title    string
	Content  string
	Verdict  string
	// -1 Stands for not-checked yet, 0-9 is actual rating
	Rating    int64
	CreatedAt time.Time
}

type Author struct {
	ID          int64
	Name        string
	Description string
	// -1 Stands for not-checked yet, 0-3 is actual rating
	Rating    int64
	CreatedAt time.Time
}
