// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateArticle(ctx context.Context, arg CreateArticleParams) (Article, error)
	CreateAuthor(ctx context.Context, arg CreateAuthorParams) (Author, error)
	DeleteArticle(ctx context.Context, id int64) error
	DeleteAuthor(ctx context.Context, id int64) error
	GetArticle(ctx context.Context, id int64) (Article, error)
	GetArticlesCount(ctx context.Context) (int64, error)
	GetAuthor(ctx context.Context, id int64) (Author, error)
	ListArticles(ctx context.Context, arg ListArticlesParams) ([]Article, error)
	ListAuthors(ctx context.Context, arg ListAuthorsParams) ([]Author, error)
	UpdateArticleRating(ctx context.Context, arg UpdateArticleRatingParams) (Article, error)
	UpdateAuthorRating(ctx context.Context, arg UpdateAuthorRatingParams) (Author, error)
}

var _ Querier = (*Queries)(nil)
