env: "local"

storage:
  driver: "postgres"
  address: "postgresql://postgres:qwerty@localhost:5444/deeptruth/?sslmode=disabled"

http_server:
  address: "localhost:8080"
  timeout: 4s
  idle_timeout: 60s
